## Network Summary

In [68]:
# Add button to toggle code on/off
from IPython.display import HTML

HTML('''<script>
code_show=true; 
function code_toggle() {
 if (code_show){
 $('div.input').hide();
 } else {
 $('div.input').show();
 }
 code_show = !code_show
} 
$( document ).ready(code_toggle);
</script>
<form action="javascript:code_toggle()"><input type="submit" value="Click here to toggle on/off the raw code."></form>''')

In [1]:
import os
import numpy as np
import pandas as pd
import h5py
import pylab as P
from IPython.display import display, display_pretty, Javascript, HTML
from pandas_highcharts.core import serialize
from pandas_highcharts.display import display_charts
import matplotlib.pyplot as plt
import sys

os.chdir('..')



# Show charts in notebook
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [2]:
os.getcwd()

'd:\\maps\\soundcast'

In [16]:
from scripts.EmmeProject import *
from scripts.summarize.network_summary import *

In [7]:
my_project = EmmeProject(r'projects/LoadTripTables/LoadTripTables.emp')

In [22]:
df_counts = pd.read_csv('inputs/network_summary/' + counts_file, index_col=['loop_INode', 'loop_JNode'])
df_aadt_counts = pd.read_csv('inputs/network_summary/' + aadt_counts_file)
df_tptt_counts = pd.read_csv('inputs/network_summary/' + tptt_counts_file)

counts_dict = {}
ft_summary_dict = {}
transit_summary_dict = {}
uc_vmt_dict = {}
aadt_counts_dict = {}
tptt_counts_dict = {}

#loop through all tod banks and get network summaries
for key, value in sound_cast_net_dict.iteritems():
    my_project.change_active_database(key)
    for name, desc in extra_attributes_dict.iteritems():
        my_project.create_extra_attribute('LINK', name, desc, 'True')
    #TRANSIT:
    if my_project.tod in transit_tod.keys():
        for name, desc in transit_extra_attributes_dict.iteritems():
            my_project.create_extra_attribute('TRANSIT_LINE', name, desc, 'True')
        calc_transit_link_volumes(my_project)
        calc_transit_line_atts(my_project)

        transit_summary_dict[key] = get_transit_boardings_time(my_project)
        #print transit_summary_dict

    net_stats = calc_vmt_vht_delay_by_ft(my_project)

    #store tod network summaries in dictionary where key is tod:
    ft_summary_dict[key] = net_stats
    #store vmt by user class in dict:
    uc_vmt_dict[key] = vmt_by_user_class(my_project)

    #counts:
    df_tod_vol = get_link_counts(my_project, df_counts, key)
    counts_dict[key] = df_tod_vol

    #AADT Counts:

    get_aadt_volumes(my_project, df_aadt_counts, aadt_counts_dict)

    #TPTT:
    get_tptt_volumes(my_project, df_tptt_counts, tptt_counts_dict)

1 * vauteq * (60/hdw)
296
296
1 * vauteq * (60/hdw)
296
296
296
296
1 * vauteq * (60/hdw)
296
1 * vauteq * (60/hdw)
296
296
1 * vauteq * (60/hdw)
296
296
4 * vauteq * (60/hdw)
296

In [29]:
transit_summary_dict

{'10to14':       10to14_board  10to14_time
 id
 0001    442.285706    18.665670
 0002    264.143646    15.807394
 0003    237.610870    18.067627
 0004    249.628448    15.797469
 0005    199.199677    18.505241
 0006    266.583801    19.294901
 0007    147.371964    15.597630
 0008    182.298828    16.152029
 0009     16.104164    17.398163
 0010    148.908218    11.619799
 0011     85.421143    18.797771
 0012    121.309692    20.426552
 0013    203.764374    17.635185
 0014    157.143127    14.242685
 0015    253.614899    15.955900
 0016    158.606613    25.970032
 0017    123.307480    21.743715
 0018    609.729126    39.359554
 0019     96.890297    39.936165
 0020    528.492493    39.936165
 0021    471.310883    38.775909
 0022    491.404175    38.918076
 0023     26.795059    24.100182
 0024   1331.499268    36.828438
 0025    630.917786    31.750496
 0026    326.617645    44.938354
 0027    649.370605    56.272739
 0028    734.091980    53.810867
 0029    177.248032    33.832066
 0030    154.700180    33.672150
 ...            ...          ...
 0719     32.371655    22.840372
 0720      6.067762    32.236618
 0721     15.557835    31.924242
 0722      2.374440    32.525181
 0723     12.525984     7.147459
 0724     26.440710    34.000919
 0725     38.481815    33.994621
 0726      6.284212    37.849857
 0727      2.872404    31.954170
 0728      1.065197    15.544973
 0729      0.269432    14.881618
 0730      1.418496    20.903193
 0731     27.977116    23.629763
 0732     18.421467    24.108858
 0733     13.480168    20.852104
 0734     10.893412    20.881824
 0735     10.893412    20.502880
 0736     12.946835    21.524544
 0737     22.873701    32.379021
 0738     48.605572    19.844738
 0739     51.242321    20.147839
 0740      0.100000    17.478907
 0741      3.290009    23.212650
 0742      0.000000    12.887938
 0743     55.550804     9.479478
 0744     58.215946    10.109660
 0757     23.780212    27.511446
 0758     26.715509    27.621172
 0759      0.198214     8.520000
 0760      0.000000     8.520000

 [746 rows x 2 columns], '14to15':       14to15_board  14to15_time
 id
 0001    130.595566    18.744427
 0002     86.678146    15.865676
 0003     75.101952    18.135523
 0004     84.653313    15.875393
 0005     81.140793    18.589245
 0006     56.899021    19.354801
 0007     52.319733    15.689977
 0008     73.749489    16.233917
 0009      5.419251    17.432545
 0010     50.037106    11.640523
 0011     30.261395    18.832710
 0012     42.595829    20.490793
 0013     54.491169    17.704458
 0014     58.755642    14.309037
 0015     69.674049    16.044910
 0016     53.376354    26.136307
 0017     42.816105    21.812233
 0018    128.355270    39.746193
 0019     20.662273    40.264496
 0020    112.703339    40.264496
 0021    163.694366    39.210640
 0022    168.134445    39.558411
 0023      7.930909    24.398666
 0024    291.195251    37.026299
 0025    204.392624    32.076302
 0026    107.022202    45.279442
 0027    229.770569    56.555256
 0028    185.826340    53.957741
 0029     41.922035    34.076046
 0030     43.779198    34.074734
 ...            ...          ...
 0719      6.486104    23.036217
 0720      1.191140    32.488071
 0721      4.860917    32.240700
 0722      0.503480    32.914864
 0723      3.417578     7.175468
 0724      7.469676    34.219639
 0725      9.687090    34.157654
 0726      2.870241    37.948757
 0727      0.191538    31.986429
 0728      0.325920    15.588446
 0729      0.115471    14.880565
 0730      0.647546    20.897676
 0731      8.359877    23.709616
 0732      6.282205    24.183266
 0733      5.224530    20.898611
 0734      3.670582    20.932882
 0735      3.670582    20.550371
 0736      5.224530    21.555677
 0737      9.229845    32.511356
 0738     13.711427    19.883379
 0739     11.627961    20.174641
 0740      0.000000    17.485466
 0741      0.354636    23.262608
 0742      0.000000    12.852776
 0743     13.225977     9.527755
 0744     17.041601    10.160635
 0757      6.772784    27.542458
 0758      5.085077    27.622713
 0759      0.000000     8.520000
 0760      0.000000     8.520000

 [746 rows x 2 columns], '6to7':       6to7_board  6to7_time
 id
 0001   82.318138  17.302481
 0002   94.789467  15.078695
 0003   56.902905  16.732557
 0004   25.292015  21.954708
 0005   85.004967  14.882593
 0006   77.866417  17.258198
 0007   40.281685  17.241934
 0008   75.496315  18.146072
 0009   30.230209  20.568832
 0010   25.796329  14.506374
 0011   42.042892  17.933096
 0012    8.646599  14.923872
 0013   31.501497  16.330412
 0014    8.664373  10.899290
 0015    7.388339  17.662281
 0016   21.021446  18.979980
 0017    1.442902  12.231158
 0018   52.680176  16.422567
 0019   12.138385  18.288242
 0020    5.159266  14.506374
 0021   43.650871  13.332439
 0022   55.362701  14.882818
 0023   33.854599  19.005491
 0024   41.322174  22.999899
 0025   20.889174  24.046783
 0026    3.884890  20.337358
 0027   21.774103  40.655174
 0028   71.798050  35.835274
 0029   22.418301  42.028740
 0030   74.686821  37.208839
 ...          ...        ...
 0997    5.585633  40.107910
 0998    2.724106  27.602835
 0999    5.807224  39.281811
 1000    6.242925  27.938566
 1001    9.265961  41.956997
 1002   10.328926  29.102901
 1003    6.354999  53.262409
 1004   24.158730  40.675484
 1005    4.726808  39.311886
 1006   12.335040  51.485874
 1007    1.892992  34.798367
 1008    3.468904  40.641186
 1009    1.595126  36.023842
 1010    5.284201  25.151913
 1011    2.039471  27.507607
 1012   12.915027  32.277943
 1013   11.092219  68.687057
 1014    6.150652  45.508606
 1015   16.437208  57.165405
 1016   60.677559  66.155418
 1017   18.677021  77.280655
 1018    6.802131  30.257700
 1019    9.723402  47.260834
 1020    8.425644  40.503716
 1021    8.986194  41.078938
 1022    7.688258  25.527134
 1047    3.915255  26.148684
 1048    6.400798  26.314104
 1049    2.531522   8.520000
 1050    0.000000   8.520000

 [1000 rows x 2 columns], '7to8':       7to8_board  7to8_time
 id
 0001  128.641617  17.518015
 0002  104.986832  15.188293
 0003   82.268150  16.944071
 0004   36.621040  22.216093
 0005   93.064079  15.022903
 0006  109.682724  17.454332
 0007   37.476574  17.423340
 0008  103.967339  18.511724
 0009   33.929050  20.794022
 0010   29.520262  14.708470
 0011   46.024395  18.174353
 0012    9.731395  15.097513
 0013   35.262608  16.533009
 0014   10.323125  11.073217
 0015    9.270439  17.866608
 0016   23.012197  19.222019
 0017    1.814588  12.406816
 0018   77.065643  16.677572
 0019   20.089684  18.567553
 0020    5.904052  14.708470
 0021   48.250626  13.462466
 0022   92.741028  15.086303
 0023   42.008591  19.255064
 0024   55.750095  23.421465
 0025   27.975046  24.469131
 0026    5.496799  20.588663
 0027   29.846806  41.831894
 0028   91.908440  37.001579
 0029   31.650799  43.769737
 0030  100.348305  38.939423
 ...          ...        ...
 0997    7.562840  41.582386
 0998    3.507945  28.952673
 0999    6.791851  40.673946
 1000    6.929550  29.875740
 1001   10.871765  43.611004
 1002   12.961006  30.876431
 1003    7.537779  54.768795
 1004   29.844090  42.103867
 1005    4.546941  39.723484
 1006   15.122021  52.401157
 1007    1.414429  35.182186
 1008    4.194249  41.056358
 1009    2.375578  36.472729
 1010    6.846912  25.469135
 1011    2.155668  28.032803
 1012   16.013639  33.065575
 1013   11.251590  69.566162
 1014    5.228939  46.229626
 1015   20.817831  58.401733
 1016   74.763275  66.659279
 1017   23.024946  78.578819
 1018    8.227060  31.742470
 1019   11.455223  48.592239
 1020    9.052292  42.097065
 1021   10.877724  43.042755
 1022    8.782669  27.226971
 1047    4.697523  26.298244
 1048    5.789876  26.625845
 1049    2.262746   8.520000
 1050    0.000000   8.520000

 [1000 rows x 2 columns], '8to9':       8to9_board  8to9_time
 id
 0001   97.873947  17.466581
 0002   86.703323  15.136290
 0003   69.669418  16.898113
 0004   30.932774  22.148514
 0005   78.155182  14.974176
 0006   88.415108  17.412462
 0007   27.828337  17.418211
 0008  109.865555  18.400064
 0009   25.250383  20.732952
 0010   24.993929  14.653893
 0011   39.652138  18.086693
 0012    8.202505  15.045373
 0013   26.114817  16.458290
 0014    7.649249  10.999101
 0015    6.711218  17.791590
 0016   19.826069  19.134192
 0017    1.354306  12.332401
 0018   58.744080  16.609165
 0019   14.710460  18.490299
 0020    4.998785  14.653893
 0021   41.293758  13.429150
 0022   69.545746  15.031233
 0023   32.279373  19.164997
 0024   45.815704  23.231098
 0025   23.007853  24.278597
 0026    3.854391  20.498297
 0027   24.601419  41.358879
 0028   79.691620  36.529713
 0029   25.245022  42.662647
 0030   82.617828  37.833481
 ...          ...        ...
 0997    4.346910  40.577106
 0998    2.334911  27.984110
 0999    4.834515  39.645000
 1000    4.867181  28.597492
 1001    7.082793  42.444824
 1002    8.551394  29.701853
 1003    5.312804  53.673809
 1004   19.025475  41.066765
 1005    4.642788  39.479160
 1006    8.427840  52.058292
 1007    1.747115  35.064075
 1008    2.347808  40.934483
 1009    1.981480  36.318558
 1010    3.525328  25.397421
 1011    2.102028  27.905334
 1012    8.210663  32.806702
 1013    7.733963  69.080513
 1014    4.214202  45.969509
 1015   12.617266  57.795483
 1016   50.285473  66.475014
 1017   12.157355  77.953445
 1018    4.905799  30.734268
 1019    8.058108  47.638897
 1020    6.910700  40.990639
 1021    7.092815  41.769131
 1022    6.162937  26.095604
 1047    4.909119  26.278591
 1048    3.890932  26.488777
 1049    2.150240   8.520000
 1050    0.000000   8.520000

 [1000 rows x 2 columns], '9to10':       9to10_board  9to10_time
 id
 0001   119.411972   18.505653
 0002    50.701557   15.698594
 0003    58.110172   17.886589
 0004    45.496857   15.643482
 0005    42.519264   18.298241
 0006    46.235714   19.123970
 0007    32.350868   15.369966
 0008    43.261818   15.943720
 0009     3.536075   17.280210
 0010    32.147587   11.567838
 0011    12.832788   18.679117
 0012    27.286272   20.215601
 0013    43.320362   17.477316
 0014    34.105804   14.096838
 0015    59.664829   15.810513
 0016    39.111675   25.652016
 0017    17.498087   21.590677
 0018   160.775848   38.440945
 0019    26.304487   39.325962
 0020   143.479050   39.325962
 0021    75.191780   37.961422
 0022    66.425926   38.242630
 0023     4.348118   23.675037
 0024   354.607269   36.430222
 0025    79.593994   31.289333
 0026    41.558121   44.407787
 0027   126.665924   55.231243
 0028   155.871567   52.958378
 0029    38.839691   33.310890
 0030    31.418180   33.060200
 ...           ...         ...
 0719    10.488211   22.857952
 0720     1.665359   32.230316
 0721     3.519824   31.713161
 0722     0.606569   32.237617
 0723     2.909579    7.126655
 0724     7.365897   33.758743
 0725    10.105718   33.938091
 0726     1.758589   37.641079
 0727     1.791765   31.722584
 0728     0.355294   15.486242
 0729     0.500374   14.728644
 0730     0.483333   20.594461
 0731     7.743166   23.346869
 0732     3.950210   23.769770
 0733     3.131575   20.626081
 0734     4.039258   20.796688
 0735     4.039258   20.391300
 0736     3.131575   21.340006
 0737     4.478717   32.080410
 0738    14.136261   19.708107
 0739    15.207325   20.069777
 0740     0.100000   17.239258
 0741     1.237974   22.975910
 0742     0.000000   12.802962
 0743    16.238766    9.395248
 0744    15.145438    9.989386
 0757     4.427866   27.218599
 0758     5.258636   27.397463
 0759     0.000000    8.520000
 0760     0.000000    8.520000

 [746 rows x 2 columns]}